" basic
syn on
set tabstop=2
set nobackup
set background=dark
colorscheme desert
set guifont=Courier\ New:h12
set number
set nofoldenable


" key mapping
let mapleader = "-"

" Ctrl-U, uppercase the word, and return to normal mode
nnoremap <c-u> viw<c-v>U<esc>
inoremap <c-u> <esc>lviw<c-v>U<esc>

" -ev, edit .vimrc; -sv, reload .vimrc
nnoremap <leader>ev :sp $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" -", make word => "word"
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel


" encoding for win32 Chinese display
set encoding=cp936
set fileencoding=cp936
set fileencodings=cp936,gb18030,utf-8,utf-16,big5


" Omni Completion
filetype plugin on
set omnifunc=syntaxcomplete#Complete


" TagList
" set Tlist_Ctags_Cmd=`$VIM\vimfiles\bin\ctags.exe`


" WinManager
" let g:winManagerWindowLayout='FileExplorer|TagList'
nnoremap wm :WMToggle<cr>


" MiniBufExplorer
" let g:miniBufExplMapWindowNavVim = 1 
" let g:miniBufExplMapWindowNavArrows = 1 
" let g:miniBufExplMapCTabSwitchBufs = 1 
" let g:miniBufExplModSelTarget = 1


" Grep
nnoremap <silent> <F3> :Grep<cr>
