" basic
syn on
set tabstop=2
set nobackup
set background=dark
colorscheme desert
set guifont=Courier\ New:h12
set number
set nofoldenable

" key mapping
" Ctrl-U, uppercase the word, and return to normal mode
nnoremap <c-u> viw<c-v>U<esc>
inoremap <c-u> <esc>lviw<c-v>U<esc>

let mapleader = "-"
nnoremap <leader>ev :sp $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Omni Completion
filetype plugin on
set omnifunc=syntaxcomplete#Complete

" TagList
" set Tlist_Ctags_Cmd=`$VIM\vimfiles\bin\ctags.exe`

" WinManager
" let g:winManagerWindowLayout='FileExplorer|TagList'
nnoremap wm :WMToggle<cr>

" MiniBufExplorer
" let g:miniBufExplMapWindowNavVim = 1 
" let g:miniBufExplMapWindowNavArrows = 1 
" let g:miniBufExplMapCTabSwitchBufs = 1 
" let g:miniBufExplModSelTarget = 1

" Grep
nnoremap <silent> <F3> :Grep<cr>
